root = "."
tmp_dir = "/tmp"

[build]
cmd = "make air-hook"
bin = "./mangago"
include_ext = ["go"]
#delay = 100 # ms
stop_on_error = true
send_interrupt = true
kill_delay = 1000 # ms

[log]
time = true

[color]
[misc]
clean_on_exit = true